-- Gate 1, cycle W=28 (plan 100007): the cold non-author packet gate1-packet-2026-09-01.md (governance 10714c6), applied on the mini
BEGIN IMMEDIATE;
CREATE TEMP TABLE g_pre(x INTEGER CHECK(x=24));
INSERT INTO g_pre SELECT COUNT(*) FROM lesson_proposals WHERE id BETWEEN 414 AND 437 AND status='proposed' AND route IS NULL;
UPDATE lesson_proposals SET status='rejected', route=NULL, status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=414 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=415 AND status='proposed';
UPDATE lesson_proposals SET status='rejected', route=NULL, status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=416 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=417 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=418 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=419 AND status='proposed';
UPDATE lesson_proposals SET status='reference', route='backlog', target_artifact='governance/knowledge/decisions/drafts/build-*.py (multi-target atomicity)', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=420 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=421 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=422 AND status='proposed';
UPDATE lesson_proposals SET status='reference', route='backlog', target_artifact='bellows/tools/mutation_check.py', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=423 AND status='proposed';
UPDATE lesson_proposals SET status='reference', route='backlog', target_artifact='bellows/hooks/commands/eluvian.md + bellows/status.py', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=424 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=425 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='DRAFTING_CYCLE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=426 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='DRAFTING_CYCLE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=427 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='DRAFTING_CYCLE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=428 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='DRAFTING_CYCLE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=429 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=430 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=431 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='DRAFTING_CYCLE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=432 AND status='proposed';
UPDATE lesson_proposals SET status='reference', route='reference', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=433 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=434 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=435 AND status='proposed';
UPDATE lesson_proposals SET status='rejected', route=NULL, status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=436 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=437 AND status='proposed';
CREATE TEMP TABLE g_post(x INTEGER CHECK(x=0));
INSERT INTO g_post SELECT COUNT(*) FROM lesson_proposals WHERE id BETWEEN 414 AND 437 AND status='proposed';
SELECT 'ACC='||COUNT(*) FROM lesson_proposals WHERE status='accepted';
SELECT 'REJ_NEW='||COUNT(*) FROM lesson_proposals WHERE id BETWEEN 414 AND 437 AND status='rejected';
SELECT 'REF_NEW='||COUNT(*) FROM lesson_proposals WHERE id BETWEEN 414 AND 437 AND status='reference';
COMMIT;
