-- Gate 1, cycle W=29 (plan 100020): the cold non-author packet gate1-packet-2026-09-02.md (governance be6bd2fd, session 22366c52), applied on the mini
.timeout 5000
BEGIN IMMEDIATE;
CREATE TEMP TABLE g_pre(x INTEGER CHECK(x=25));
INSERT INTO g_pre SELECT COUNT(*) FROM lesson_proposals WHERE id BETWEEN 442 AND 466 AND status='proposed' AND route IS NULL;
SELECT 'PRE='||x FROM g_pre;
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=442 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=443 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=444 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=446 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=447 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=449 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=453 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=455 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=456 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=458 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=459 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=460 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=461 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=462 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=463 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='PLANNER_TEMPLATE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=464 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='DRAFTING_CYCLE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=445 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='DRAFTING_CYCLE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=448 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='DRAFTING_CYCLE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=450 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='DRAFTING_CYCLE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=451 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='DRAFTING_CYCLE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=452 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='DRAFTING_CYCLE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=454 AND status='proposed';
UPDATE lesson_proposals SET status='accepted', route='codify', target_artifact='DRAFTING_CYCLE.md', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=466 AND status='proposed';
UPDATE lesson_proposals SET status='rejected', route=NULL, status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=457 AND status='proposed';
UPDATE lesson_proposals SET status='reference', route='reference', status_updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now'), status_updated_by='planner' WHERE id=465 AND status='proposed';
CREATE TEMP TABLE g_post(x INTEGER CHECK(x=0));
INSERT INTO g_post SELECT COUNT(*) FROM lesson_proposals WHERE id BETWEEN 442 AND 466 AND status='proposed';
SELECT 'PROPOSED_LEFT='||x FROM g_post;
SELECT 'ACC='||COUNT(*) FROM lesson_proposals WHERE status='accepted';
SELECT 'ACC_PT_NEW='||COUNT(*) FROM lesson_proposals WHERE id BETWEEN 442 AND 466 AND status='accepted' AND route='codify' AND target_artifact='PLANNER_TEMPLATE.md';
SELECT 'ACC_DC_NEW='||COUNT(*) FROM lesson_proposals WHERE id BETWEEN 442 AND 466 AND status='accepted' AND route='codify' AND target_artifact='DRAFTING_CYCLE.md';
SELECT 'REJ_NEW='||COUNT(*) FROM lesson_proposals WHERE id BETWEEN 442 AND 466 AND status='rejected';
SELECT 'REF_NEW='||COUNT(*) FROM lesson_proposals WHERE id BETWEEN 442 AND 466 AND status='reference';
SELECT 'PRIOR_UNTOUCHED='||COUNT(*) FROM lesson_proposals WHERE id <= 441 AND status_updated_at = '2026-09-01T22:03:28Z' AND status='accepted';
COMMIT;
