#!/usr/bin/env python3
# Gate-2 batch 3 builder - DRAFTING_CYCLE v2.2 -> v2.3.
# All-or-nothing: reads SRC once, asserts every anchor BEFORE any mutation,
# applies all six edits in memory, writes DST once. Assert failure => zero bytes written.
import io, sys

SRC = sys.argv[1]
DST = sys.argv[2]
s = io.open(SRC, encoding='utf-8').read()
edits_applied = []

def rep(old, new, expect=1, label=""):
    global s
    got = s.count(old)
    assert got == expect, f"ANCHOR COUNT {label}: expected {expect}, got {got} for {old[:60]!r}"
    s = s.replace(old, new, expect)
    edits_applied.append(label)

def b(pid, text):
    return f"- {text} *(Proposal {pid}, codified 2026-08-11.)*"

# ---------------- E1: section 2.6 block (4 items), inserted before the 2.7 heading
S26 = "\n".join([
b(227, "**Newest-of-class is a MEASUREMENT, not an assertion.** Before claiming any plan is the newest of its class, sort the shipped set by ship date and name the winner WITH its date, as a measured line in the plan. Measured cost of skipping it: an ACID pass spent a finding rediscovering a hardening a sibling had shipped one day after the claimed newest."),
b(254, "**Diff the parent's FINAL text, and ask whether the parent amended each inherited guard after first writing it** (extends the clone-diff rules above). A clone that rewrites a guard from its purpose imports the parent's ORIGINAL form — measured: a restored guard imported the pre-fold unscoped version of a guard the parent had scoped mid-cycle, and it would have blocked three questions that needed nothing from the missing input. Clone-drift has three depths: guards absent, guards present but unqualified, and corrections reaching some sites but not all."),
b(283, "**After any fold that NARROWS a check's candidacy (filter, exclusion, allowlist), re-trace every cited evidence case through the narrowed spec and confirm each can still fire.** A Why-table citation is a claim about the SHIPPED shape, not the prototype's — re-verify the pairing whenever either side moves. Measured: a check's cited evidence consisted entirely of cases its own new exclusion filtered out — the census's only measured true positives were exactly what the exclusion removed from candidacy."),
b(286, "**Aim panel seats at deletion premises and the clone-diff explicitly — the register's plain lenses under-produce cold.** Run the mechanical residue battery (lint + consistency sweeps) after EVERY culmination, so cold readers hunt novel defects rather than their predecessors' sync debt. Meter every panel and compare against the standing baseline (563k tokens / 45 findings, the first metered run — every HIGH came from the two aimed briefs; the lens-replication seats produced MEDIUM hardening). The seat-brief registry above carries the brief text; this bullet fixes the residue-battery cadence and the metering convention."),
])
H27 = "### 2.7 Cross-cutting rules (apply within every walk)"
rep("\n" + H27, "\n" + S26 + "\n\n" + H27, 1, "E1-s26-block")

# ---------------- E2: section 2.7 block (23 items), inserted before the 2.8 heading
S27 = "\n".join([
b(231, "**Any marker whose practical meaning is 'I did not run this' gets the INHERITED cost test regardless of its spelling** (extends the lens-attestation clause above). A clone that re-imports an identical excuse under a new marker name has laundered it past the rule — apply the test to the meaning, not to the one name the rule happens to use. Measured: a clone quoted the governing rule approvingly and then violated it under a renamed marker."),
b(234, "**Verify a deletion by the absence of the construct's CONTENT (its assertion text, its query), never by the absence of its label; excise the WHOLE SPAN of a multi-line construct** (extends the subtractive-trim clause above). Measured: a check was 'deleted' by removing its label line while the body — a fenced query and three assertions — survived six lines below, and the post-condition asked only whether the label string was gone."),
b(235, "**Budget a cut as an EDIT that will generate findings, not as a subtraction that reduces them.** After removing anything, sweep for references TO it and for captures that just lost their only reader — those are the two mechanical failure modes. Do not preserve numbering to protect references to removed items; measured: every reference that broke was to a deleted row, and the cut produced six dangling cross-references, two orphaned captures, and a stale justification clause."),
b(237, "**Never pipe a command whose exit code carries meaning** (extends the command-output clause above): the shell reports the LAST command's status, so a formatter's success silently replaces the checker's failure. Capture output to a variable or file, then inspect and report the code separately. Measured: four independent readers in one session fell to the same pipe-masked exit code."),
b(241, "**Enumerate every applicable site BEFORE applying a fix anywhere, with sweep weight highest on material written in the SAME SESSION as the fix.** The author who has just formulated a rule is the one least likely to re-scan for other instances — formulating it feels like discharging it. Measured: two same-shape HIGH findings each fixed at one site with the sibling site untouched, the second defect added in the same edit session as the first one's fix."),
b(248, "**A consumer sweep probes for the CLAIM in any phrasing — enumerate the sections that could plausibly hold it; never grep only the string you just edited.** A sweep built from one's own wording confirms only what was edited, and a retraction that specifies a count ('corrected in three places') gives false confidence. Measured: a fifth site held the same claim as a paraphrase the literal probe could not match."),
b(249, "**When a guard's safety depends on a claim about text, EXECUTE the guard's actual matcher — never reason about it — and report which branch fired and what it captured.** Measured: a gate was safe only by the accident of an incidental backtick; reasoning said 'probably fine', and running the real regexes showed one removed character away from capturing prose as a declared deposit list."),
b(251, "**Any probe over a plan that carries retractions must CLASSIFY each hit — instruction or retraction-of-instruction — before reporting.** A well-run cycle deliberately accumulates text of the form 'an earlier form said X — X was wrong', and every such retraction is a literal instance of X. Measured: two of seven probes fired false alarms on retraction text, and one would have been folded unchecked."),
b(252, "**Closing-line ordering: walk → culminate → final ACID → then close, with every count stated AS OF a named completed phase.** A closing line written one phase early is not merely incomplete — it is flattering by precisely the margin the missing phase would have removed. Measured: a fifth owed ACID pass found all three of an early-written closing line's claims defective."),
b(253, "**Anchor every structural search line-anchored, and strip fenced blocks and blockquotes before matching any token that also appears in prose** (companion to the count-is-not-value clause above). A document about a convention QUOTES that convention — decoy density is highest in exactly the files most likely to be measured. Measured: nine prose mentions of a heading token caused four misfired measurements in one session, one landing 251 lines early."),
b(256, "**Ask whether convenient facts make your own argument work before trusting them: re-read populations from the upstream table ROW BY ROW between sections, and diff same-population sites against each other.** A flattering substitution is not random — it is selected by the argument it rescues. Measured: a swap of two entry attributions that made a motivating claim true survived a walk, a culmination, an ACID pass and a second culmination."),
b(261, "**Three probe-integrity clauses from a four-for-four false-absence session:** zsh does not word-split unquoted parameter expansions, so a two-variable probe silently takes the whole string into the first and empties the second — a failure identical in shape to a true negative; a RECORDED relative path rarely resolves against the current repo — resolve each against its OWN project root before declaring the file missing; and a standard written for an agent binds the PLANNER too — verification discipline does not relax at authoring time. Measured: four confident NOT-FOUND lines, all four wrong, all four archived exactly where they should have been."),
b(262, "**A conformance probe must match the artifact's REPRESENTATION (regex, table, computed form), not the spec's prose literals** (companion to the grep -F clause above). Before recording an absence, read the implementation site; the positive control must use the SAME representation as the target. Measured: two panel-critical hardenings looked ABSENT because the spec's literals ship as regexes, and a literal probe cannot see a spec literal implemented as a pattern."),
b(263, "**After any fold, re-verify every factual claim in the fold's OWN text against the post-fold artifact** — counts, presences, behaviours: a fold edits the artifact AND silently invalidates the prose describing the fold. When a fix must reference the hazardous token it removes, reference it by description or measurement, never by exhibiting it; and author-verify a proposed fix by the same method that found the defect. Measured: a delimiter fold's replacement sentence still claimed the glyph occurred 'exactly once' after removing the occurrence it counted — and a cold reader's proposed fix spelled the new delimiter as a glyph, re-planting the bomb."),
b(270, "**A presence check for content that can duplicate INTRA-LINE uses the occurrence form (`grep -Fo | wc -l`), never `-c`** (companion to the count-is-not-value clause). A re-applied in-place tail extension lands both copies on ONE line: every `-c` count still prints 1 and a sha pin then certifies the corruption. Validate the instrument against a CONSTRUCTED failure, not only the success path — the occurrence form prints 2/1/0 across doubled/correct/absent, validated by execution."),
b(279, "**For large classification batches, prefer manifest-pinned tranches over a single saturated step, and carry the per-tranche depth distribution (floor, ceiling, ratio range) as the standing calibration instrument across cycles.** Validated at 3.2× the record batch with no inter-tranche cliff — and the measured risk at that scale was never classification quality but RESUME complexity, where all of the cycle's high-severity drafting findings lived."),
b(287, "**Any population a measurement depends on is enumerated MECHANICALLY (`git log --follow` by path, `SELECT` by key range) — a narrated count is a label, never the filter or the gate.** When two sections of one artifact each state a total over the same population, emit the reconciliation line at authoring; a reader-visible gap without one is a defect. Measured: four of four close-commit drafting-counts disagreed with path enumeration, and the measuring deposit then carried the same class inward (190 declared vs 174 classified, never cross-reconciled)."),
b(290, "**Every constructed or variable pattern is passed via `-e \"$PAT\"` (or after `--`)** (companion to the grep -F clause — '-F is mandatory' does not cover it). A run-time-concatenated pattern beginning with a dash errors as an unrecognized option with NOTHING on stdout. And note the composition trap: two independently-correct hardenings can compose into a failure when one normalizes the symptom of the other."),
b(295, "**For any sweep of a phrase whose fixes cite the original, verify by CLASSIFICATION — list every hit and mark each operative or correction — never by count.** The count never trends to zero: each fold records what it corrected, so the corrected wording survives inside the correction; one measured recount came back HIGHER than before the fold. Zero OPERATIVE hits is the pass condition; the total is meaningless."),
b(298, "**When any premise is corrected, grep the artifact for every guard resting on it and re-justify or remove each one — the correction is not complete at the site where the premise was stated.** An agent that can see through a guard's stated reason steps over the guard: the REASON is what carries authority in practice, because the reason is what an agent weighs when the rule is inconvenient. Measured: a hard read-only guard survived the measurement that falsified its own justification."),
b(300, "**Any claim that a governed text CHANGED — tightened, loosened, added, removed — is established by `git show <old>:<file>` against the live file, never by the changelog row** (applies in §2.6 clone work and here alike). A History row is accurate and directionally silent; a reader supplying the direction supplies the one that fits the story being written. Run one pass over a cycle's own conclusions record at the evidence standard the cycle enforced on its subject. Measured: a published, committed, pushed 'tightened' that one `git show` proved was 'loosened'."),
b(304, "**Before computing from a record, count its DIALECTS — sample the shape, not just the presence.** Make 'unparseable' a REPORTED outcome with the offending line attached, never a skip; ask structural questions with structural probes, not file-level searches. Measured: one corpus carried three record forms; the target field was machine-readable in 0 of 61 logs while a file-level grep reported it present."),
b(311, "**For any absence claim, derive the probe FROM the target text — open the file and copy the string — never compose it from memory.** A zero from a composed probe is a hypothesis; a zero from an extracted probe is evidence. Enumerate what IS there and read it, rather than asserting what is not. Measured: six composed-probe false absences in one session, all on verification steps; five would have licensed a wrong action."),
])
H28 = "### 2.8 Conflict Ledger (keeps cross-lens folds from oscillating)"
rep("\n" + H28, "\n" + S27 + "\n\n" + H28, 1, "E2-s27-block")

# ---------------- E3: section 2.8 block (4 items), inserted before the closing paragraph
S28 = "\n".join([
b(224, "**An enumerating constraint decays as oscillation, and the tell is the SECOND reversal, not the first.** A constraint corrected in one direction and then the other is enumerating, not converging — restate it as the PRINCIPLE the list was approximating rather than improving the enumeration. Measured: a ledger constraint oscillated through three formulations, each individually well-reasoned."),
b(272, "**Foreign constraint and finding ids are ALWAYS namespaced** (`plan-301's C24(a)`, `diag-302's C7`) — and when a fold applies a rule, verify the rule has a LOCAL ledger row: applying an unledgered rule is how a repeatedly-violated constraint stays invisible. Measured: a fold cited a bare id meaning another plan's constraint while the local id was an unrelated premise — the rule actually applied was ledgered nowhere and twice violated."),
b(276, "**After ANY fold, re-check it against the ledger's NEWEST constraints specifically** — the newest are the most breached, because subsequent folds embody habits that predate them. Three same-cycle breaches of freshly-opened constraints is the strongest evidence for pricing MECHANIZATION of a constraint over another prose restatement. Measured: three constraints opened from the very batch being processed, each then violated by a later fold in the same cycle."),
b(296, "**When a constraint is opened mid-cycle, run its check over the WHOLE artifact immediately — as part of opening it, not at the next culmination — and record the sweep result in the constraint row itself.** Opening a constraint feels like closing the class; it is not: it binds what is written after it, and everything already in the artifact is grandfathered in silently. Measured: a non-ASCII-probe constraint opened at walk 1 was violated at two load-bearing pins written BEFORE it existed; twenty lens passes read past them."),
])
TAIL28 = "\nThe ledger makes the cross-requirement constraint set"
rep(TAIL28, "\n" + S28 + "\n" + TAIL28, 1, "E3-s28-block")

# ---------------- E4: section 3 block (5 items), inserted after the reflexive-prohibition paragraph
S3 = "\n".join([
b(260, "**When declaring a tier whose gate you cannot yet satisfy, phrase the status line so it CANNOT match the gate's pattern until the condition is true, and rewrite to canonical form only once earned** (extends the earned-phrasing clause above). An EARNED warning ships unsilenced. Measured: a v0 with zero lens passes returned cleaner gate output than the same file after three walks, because 'not run' contains no fold-token — the gate was silent on the plan with no review and spoke on the one with the most."),
b(273, "**When a gate misreads an HONEST record, read the check's implementation and reword only when the truer statement is also the legible one** — never satisfy a checker with wording the state has not earned; the reword must increase accuracy, not just legibility. Probe-must-match-representation applies to WRITING records, not only reading them. Measured: a dry pass recorded in prose rows the closing-check's regex cannot match kept a WARN alive; recording it per-lens was simultaneously more accurate and checker-legible, and the WARN cleared earned."),
b(285, "**Beside every record a mechanical check reads, state the check's exact matching semantics and the earned-clear condition — and pre-classify the OVER-MATCH band.** A verifier built independently of its target both over-matches (flagging correct records) and under-matches (clearing incorrect ones); a verifier fire is a QUESTION about which side is right, not automatically a defect in the target. Measured: three specimens in one session — a WARN that cleared one phase early, a retraction that tripped a phrase-match by quoting the caught phrase, and a halt check built broader than its exclusion."),
b(309, "**When a record must mention a value a gate keys on, DESCRIBE it rather than reproduce it — including inside corrections and retractions.** After any record edit, re-run the gate and diff the WARN set against its prior state, treating a disappearance as a defect until explained. (The automated WARN-set diff is bellows-owned — FORWARD 50; this is the authoring half.) Measured: a struck token inside a retraction satisfied a negation-stripping check — the edit touched only the record and changed only the gate's verdict."),
b(313, "**Record sections — the Cycle Log and any register material — are placed OUTSIDE every step's span: above the first step heading, never trailing after the last step.** The final QA step's gate span absorbs a trailing record, and the class fired four times in one walk under a rule that already forbade it — when a hazard recurs under a rule that forbids it, measure the recurrence and change the GEOMETRY rather than hardening the wording. (The gate-span regex fix is bellows-owned — FORWARD 45; this is the placement half.)"),
])
ANCH3 = "including to the sentence that warns against quoting them."
rep(ANCH3, ANCH3 + "\n\n" + S3, 1, "E4-s3-block")

# ---------------- E5/E6: version + History ----------------
rep("**Version:** 2.2 (2026-08-11). Amended only through the Iteration Protocol",
    "**Version:** 2.3 (2026-08-11). Amended only through the Iteration Protocol", 1, "E5-version")

HIST = "## History\n"
ROW = ("- **2.3 (2026-08-11):** slug gate2-dc-batch-2026-08-11; Gate-2 codification of 36 proposals — the corpus path proper, no §6 deviation; "
"the largest DRAFTING_CYCLE batch (21 routed by the 2026-08-09 gate via plan 326, 15 by the 2026-08-11 gate via plan 342; all 36 flipped "
"accepted-to-implemented by this plan). Landed as four section-end bullet blocks, append-only, zero mid-line edits: §2.6 +4 (227 newest-of-class "
"as measurement, 254 diff-parent-final-text, 283 candidacy-narrowing re-trace, 286 panel aim/residue-battery cadence/metering baseline); §2.7 +23 "
"(231, 234, 235, 237, 241, 248, 249, 251, 252, 253, 256, 261, 262, 263, 270, 279, 287, 290, 295, 298, 300, 304, 311 — probe integrity, sweep "
"discipline, closing-line ordering, population enumeration, tranche calibration); §2.8 +4 (224 oscillation-tell, 272 namespaced ids, 276 "
"newest-constraint re-check, 296 sweep-on-open); §3 +5 (260 earned-phrasing extension, 273 legible-and-true rewording, 285 over-match "
"pre-classification, 309 describe-not-reproduce with the FORWARD 50 split, 313 record-placement geometry with the FORWARD 45 split). Rule-46 "
"splits stay bellows-owned and are named inline where they occur. §6 coordinate-doctrine-and-gate discharged by measurement: the gate reads "
"plan files, not this doctrine; token sweep against plan_lint.py and gates.py recorded in the shipping plan's QA. Inheritors: the §2 rewrite "
"(the last queued batch) and every future cycle.\n")
rep(HIST, HIST + ROW, 1, "E6-history")

io.open(DST, 'w', encoding='utf-8').write(s)
print(f"OK — {len(edits_applied)} edits applied: {', '.join(edits_applied)}")
